'use client';

import ConfirmationProvider from '@/providers/confirmation';
import { store } from '@/rtk/configureStore';
import { Geist, Geist_Mono } from 'next/font/google';
import { Provider } from 'react-redux';
import { Toaster } from 'sonner';

import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provider store={store}>
      <ConfirmationProvider>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            {children}
            <Toaster position="top-right" />
          </body>
        </html>
      </ConfirmationProvider>
    </Provider>
  );
}
